### ISSUE TITLE
Permission denied error within _build directory

### ISSUE THREAD

**Issue by timwis** [bitwalker/alpine-elixir-phoenix#48]
Hello, I'm using the example Dockerfile from the README with the only change being I've set `MIX_ENV=dev` in it since I'm only using it for development for the minute anyway. It compiles fine, but when I run my server, I get the following error:

```
server_1    | [error] GenServer :tzdata_release_updater terminating
server_1    | ** (File.Error) could not write to file "/opt/app/_build/dev/lib/tzdata/priv/latest_remote_poll.txt": permission denied
server_1    |     (elixir) lib/file.ex:1014: File.write!/3
server_1    |     (tzdata) lib/tzdata/data_loader.ex:43: Tzdata.DataLoader.last_modified_of_latest_available/1
server_1    |     (tzdata) lib/tzdata/release_updater.ex:79: Tzdata.ReleaseUpdater.loaded_tzdata_matches_remote_last_modified?/0
server_1    |     (tzdata) lib/tzdata/release_updater.ex:40: Tzdata.ReleaseUpdater.poll_for_update/0
server_1    |     (tzdata) lib/tzdata/release_updater.ex:17: Tzdata.ReleaseUpdater.handle_info/2
server_1    |     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
server_1    |     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
server_1    |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
server_1    | Last message: :check_if_time_to_update
server_1    | State: []
server_1    | 20:25:32.071 [error] CRASH REPORT Process tzdata_release_updater with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"write to file">>,path => <<"/opt/app/_build/dev/lib/tzdata/priv/latest_remote_poll.txt">>,reason => eacces} in 'Elixir.File':'write!'/3 line 1014
server_1    | 20:25:32.072 [error] Supervisor {<0.273.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Tzdata.ReleaseUpdater' started with 'Elixir.Tzdata.ReleaseUpdater':start_link() at <0.279.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.File.Error',action => <<"write to file">>,path => <<"/opt/app/_build/dev/lib/tzdata/priv/latest_remote_poll.txt">>,reason => eacces} in 'Elixir.File':'write!'/3 line 1014 in context child_terminated
```

I've tried `chown default -R /opt/app/_build` and this doesn't fix it. `latest_remote_poll.txt` is still owned by `root`. Any idea what could be going on here?

**Comment by bitwalker** [comment]
Something in your build is writing that file, you should run the `chown` command at the very end of your build to ensure nothing is left with root ownership attached.
